apiVersion: apps/v1
kind: Deployment
metadata:
  name: talaba-worker
  namespace: talaba
  labels:
    app: talaba-worker
    tier: backend-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: talaba-worker
  template:
    metadata:
      labels:
        app: talaba-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/oktamovsanjar/talaba-bot:latest
          command: ["celery", "-A", "apps.workers.celery_app.celery_app", "worker", "--loglevel=INFO", "-c", "4"]
          envFrom:
            - configMapRef:
                name: talaba-global-config
            - secretRef:
                name: talaba-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
